- name: Install httpd
  hosts: 192.168.110.23
  become: true
  tasks:
    - name: Install required packages
      package:
        name: httpd
        state: present
    - name: Create index.html if not exists
      blockinfile:
        path: /var/www/html/index.html
        block: |
          <h1>Serving content from server WebServer103</h1>
          <img src=https://zipmex.com/static/e3e07905769dbbe548f4e593d6f6e3a1/1bbe7/Web-3.0-Explained.jpg>
        create: true
    - name: Set firewall rules for port 80/tcp and 80/udp
      firewalld:
        port: "80/tcp"
        permanent: yes
        state: enabled
    - name: Reload Firewall
      command: firewall-cmd --reload
    - name: Start HTTPD service and enable it on boot
      systemd:
        name: httpd
        state: started
        enabled: yes

  handlers:
    - name: Start HTTPD service
      systemd:
        name: httpd
        state: started
        enabled: yes      