- name: Sample yaml file to install multiple packages
  hosts: all
  become: true
  tasks:
    - name: Install required packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - bind-utils
        - ntp