- name: Install bind bind-utils ntp
  hosts: primary
  become: true
  tasks:
    - name: Install required packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - bind-utils
        - bind
        - ntp