---
- name: Configure named.conf
  hosts: nsprimary
  become: true
  tasks:
    - name: Ensure named directory exists
      file:
        path: /var/named
        state: directory

    - name: Create ziyotek.local forward lookup zone file
      file:
        path: /var/named/ziyotek.flz
        state: touch

    - name: Create 110.168.192.in-addr.arpa reverse lookup zone file
      file:
        path: /var/named/ziyotek.rlz
        state: touch

    - name: Edit named.conf
      become: yes
      lineinfile:
        path: /etc/named.conf
        #regexp: '^#BEGIN_NAMED_CONF_CONFIG'
        #insertafter: '^#BEGIN_NAMED_CONF_CONFIG'
        line: |
          options {
              listen-on port 53 { 127.0.0.1; 192.168.110.12; };
              listen-on-v6 port 53 { ::1; };
              directory     "/var/named";
              dump-file     "/var/named/data/cache_dump.db";
              statistics-file "/var/named/data/named_stats.txt";
              memstatistics-file "/var/named/data/named_mem_stats.txt";
              recursing-file  "/var/named/data/named.recursing";
              secroots-file   "/var/named/data/named.secroots";
              allow-query     { localhost; 192.168.110.0/23; };
              allow-recursion { localhost; 192.168.110.12; };
              allow-transfer  {localhost; 192.168.110.13; 192.168.110.14; };
              also-notify { 192.168.110.13; 192.168.110.14; };
              recursion yes;
              dnssec-enable yes;
              dnssec-validation yes;
              bindkeys-file "/etc/named.root.key";
              managed-keys-directory "/var/named/dynamic";
              pid-file "/run/named/named.pid";
              session-keyfile "/run/named/session.key";
          };

          logging {
              channel default_debug {
                  file "data/named.run";
                  severity dynamic;
              };
          };

          # FORWARD LOOKUP ZONE
          zone "ziyotek1.local" IN {
              type master;
              file "ziyotek.flz";
              allow-update { none; };
          };

          # REVERSE LOOKUP ZONE
          zone "110.168.192.in-addr.arpa" IN {
               type master;
               file "ziyotek.rlz";
               allow-update { none; };
          };

        #backrefs: yes

    - name: Copy named.localhost to ziyotek.flz
      command: cp -p /var/named/named.localhost /var/named/ziyotek.flz
      ignore_errors: yes

    - name: Copy named.loopback to ziyotek.rlz
      command: cp -p /var/named/named.loopback /var/named/ziyotek.rlz
      ignore_errors: yes    