- name: Install bind bind-utils 
  hosts: nssecondary
  become: true
  tasks:
    - name: Install required packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - bind-utils
        - bind